version: '3'

services:

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      #        - db_data:/var/lib/mysql
      #        - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

  app:
    build: ./BackEnd
    links:
      - db
    ports:
      - "5000:5000"







